### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#10]
We ought to have a nice version numbering scheme. I vote for [Hackage's PVP](https://www.haskell.org/haskellwiki/Package_versioning_policy). 

If you are familiar with semantic versioning:

```
1.2.3
| | |
| | - Code changes with no API change
| --- API additions (or an addition of a feature)
----- API breaking changes (or a removal of a feature)
```

Hackage PVP versioning:

```
0.1.2.3
| | | |
| | | - Code changes with no API change
| | --- API additions (or an addition of a feature)
| ----- API breaking changes (or a removal of a feature)
------- Major new versions (this way we can say "version 1" or "version 2")
```

In the case of a book, this would be

```
0.1.2.3
| | | |
| | | - Trivial changes
| | --- New content
| ----- Removal of content
------- Major version
```

**Comment by ghost** [comment]
Since there is no breaking changes, and the project isn't haskell centric, I see no reason to stick to anything over a generic versioning system. However, it's also worth saying that this is a discussion that doesn't matter until we've got a 'copy' of the book. We can have these sorts of discussions when they're relevant.

**Comment by pharpend** [comment]
Alright then, I agree.
