### ISSUE TITLE
Contact /r/learnmath about namespace conflict

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#14]
We've registered both an organization on GitHub and an IRC channel which uses the "learnmath" name. I recommend that we contact /r/learnmath to inform them of this. Firstly, it's not too late to shift. Secondly, considering that we are a very young organization, there is still time for us to rename the organization/register another channel. Thirdly, /r/learnmath has existed for 5 years while it's been barely a few months ever since this project started.

Thanks to pharpend who pointed this out in https://github.com/learnmath/lysa/issues/8#issuecomment-67148066.

**Comment by pharpend** [comment]
Agreed. Who has a reddit account?

I might have one, I'm not sure.

**Comment by ghost** [comment]
I'll do it, but I have no idea what to say? "You're learnmath, We're learnmath, let's do lunch?"

**Comment by pharpend** [comment]
Maybe something to the effect of

> Hey, I created the `#learnmath` IRC channel on FreeNode a while back, not
> realizing there may be a namespace conflict with you guys, if you were to ever
> stroll over to IRC.
> 
> ... explain LYSA
> 
> We would be willing to link to your subreddit in our website and channel
> /topic if y'all'll put a link to us in your sidebar.
> 
> Thanks,
> 
>  beingbrown

?

**Comment by ghost** [comment]
Hey Glorious Mods:

I spend time on IRC in programming channels answering math questions, so I decided to create #learnmath on FreeNode a month or so ago. I am not very active on reddit, so I did not realize there was a namespace conflict.

After the creation of the channel, a few others and myself decided to also write a math book! Learn You Some Algebra is a book that hopes to make sense of mathematics from the ground up. You can find the source here <link>. Because of the channel we'd used, we similarly named the github organization.

I want to first say I'm entirely sorry for the namespace conflict. That's why I'm reaching out now: I'm wondering if we can continue on together, in affiliation, sharing the namespace (we'd link the reddit on irc), or if we need to find a new namespace. I look forward to working with you!

beingbrown

**Comment by pharpend** [comment]
They aren't necessarily programmers, so "namespace" might sound like a word you made up to make yourself sound smart. Other than that, it's good.

Also make sure to provide links

**Comment by pharpend** [comment]
@beingbrown Any update on this?

**Comment by ghost** [comment]
Message sent, waiting on response.

**Comment by pharpend** [comment]
Alright.

**Comment by ghost** [comment]
Response:
Yeah man I'm totally down to have that happen!

I've emailed for a little more formal clarity, but I think we're good to go--I'm closing this issue.

**Comment by pharpend** [comment]
Awesome.
