### ISSUE TITLE
Bots disconnect and quit

### ISSUE THREAD

**Issue by DTSCode** [learnmath/lysa#31]
Is it possible to get the github/travis service bots to stay on the channel permanently, instead of the current JOIN -> message -> PART scheme? Other channel members are starting to get restless.

**Comment by pharpend** [comment]
Are we just going to assign & unassign people at random? Because that sounds fun?

**Comment by DTSCode** [comment]
sure. It was my damn mouse. I meant to assign it to @wei2912, since I thought he was spear heading it, but my crappy track pad thought you and I looked just as good

**Comment by pharpend** [comment]
Well, I added colors. This isn't @wei2912's problem, this is @beingbrown's issue with the channel modes. Thus, reassigning

**Comment by wei2912** [comment]
Nope, but you can avoid the join part spam using external messages.

Or we could use a separate IRC channel.

**Comment by pharpend** [comment]
I mentioned this in the channel, I think using a separate channel is overkill, because most of the discussion in #learnmath is about the project. This also wouldn't fix the core problem which is, every time I made a change, I had to tell other people "hey, I made this change, go look at it". If people have to look in a separate channel, the problem still exists, but in a different form.

**Comment by ghost** [comment]
I'm hoping math conversations pick up on the irc. when we're going to be doing tons of active work, it might be a good idea to mute them if interesting conversation is happening.

**Comment by pharpend** [comment]
I have #lysa reserved on FreeNode, so we could move the book conversation over there if need be.

**Comment by wei2912** [comment]
Merging into the master branch shouldn't happen very often, so there won't be a lot of traffic.

**Comment by pharpend** [comment]
On the contrary actually, according to the contrib guide, merging should happen frequently.

Anyway, here's a screenshot representing the issue:

![](http://i.imgur.com/79vJizr.png)

**Comment by wei2912** [comment]
Well, what I said doesn't apply for the other branches, and we're showing commits to all branches.

**Comment by wei2912** [comment]
Any thoughts on allowing external messages?

**Comment by pharpend** [comment]
I'm in favor of it - it doesn't seem to be an issue with channels that have -n. It's ultimately up to @beingbrown, though

**Comment by ghost** [comment]
My honest take is that at this point join/part aren't the problem (it might be worth evaluating the amount of notifications the bots make, however), and if at any point they are, the actual quantity of messages will be an equal problem that will need to be addressed. I do think we should look into rolling a gp bot that will handle both functions and will have extended use to stay in the channel.

**Comment by pharpend** [comment]
My reasoning - 
- I have weechat filter join/part messages, except from those who spoke recently. So really the only join/part messages I'm seeing are from lysabot.
- We already allow notices to be sent from outside the channel. Notices are much more annoying than messages (in that a notice highlights everybody), but we don't seem to have a problem with that.
- There aren't any problems in other channels that have -n.
- It would be a considerable effort to have a bot that alerts when we commit - especially because the current bot is a feature of GitHub, in that it's a hook invoked whenever someone pushes a commit. Our own bot would have to repeatedly query GitHub for new commits, which seems horrible. Not to mention, someone would have to write the bot. 
- There are always multiple operators in the channel - at least there have been recently - so we can kick/ban troublemakers if need be.
- Watching in the channel for troublemakers is a lot less annoying than seeing join/part messages. (For me, at least).

All of these things make me want to set the channel mode to `-n`.

**Comment by pharpend** [comment]
Correct me if I'm wrong, @beingbrown, but this seems like something that isn't important to you? With that in mind, I'm closing as WONTFIX.
